### ISSUE TITLE
Watches not loading

### ISSUE THREAD

**Issue by wilburcoding** [SteepAtticStairs/AtticRadar#4]
I cannot seem to load severe thunderstorm watches.
![image](https://github.com/SteepAtticStairs/AtticRadar/assets/66228004/17211b19-b4bd-4188-be15-9696c8670624)
![image](https://github.com/SteepAtticStairs/AtticRadar/assets/66228004/b3476e24-6723-49ea-91bd-12383cceb61f)

**Comment by wilburcoding** [comment]
Also would like to point out that enabling watches but not enabling show alerts still shows the alerts automatically.

**Comment by SteepAtticStairs** [comment]
Thanks for the report!

I can easily fix the second thing you mentioned - good catch, I didn't about that at all!

As for the severe thunderstorm watches, this is something that I am aware of. AtticRadar fetches alert data client-side straight from the NWS, e.g. [`https://api.weather.gov/alerts/active`](https://api.weather.gov/alerts/active). However, not all alerts have a polygon directly associated with them. For example, tornado warnings have specific polygons issued on a case-by-case basis, and they are included in that URL I gave above. However, less severe alerts, e.g. watches, are simply issued to a forecast zone. These zones have their own polygons, but there are far more complex, and they aren't included in that URL.

Right now, I'm working on compiling all forecast zones' geometry into a master dictionary, and then simplifying them. This was implemented in a previous version of AtticRadar, but disabled since the dictionaries were 30+ MB total, which is ridiculous.

You can expect to see both things resolved very soon.

**Comment by SteepAtticStairs** [comment]
> Also would like to point out that enabling watches but not enabling show alerts still shows the alerts automatically.

This has now been resolved with [`9afc55c`](https://github.com/SteepAtticStairs/AtticRadar/commit/9afc55ccf39455ef9ae0385f1d064ee90d7e5850)

**Comment by SteepAtticStairs** [comment]
> I cannot seem to load severe thunderstorm watches.

This has now been resolved with [`5b594d8`](https://github.com/SteepAtticStairs/AtticRadar/commit/5b594d8947c2c69218cb2fef94236d248dd99ec5)

**Comment by wilburcoding** [comment]
Looks like it still doesn't work for me. Could be an issue on my end.

**Comment by SteepAtticStairs** [comment]
Nope, this is my fault - I temporarily disabled those dictionaries because there were some minor issues, but I didn't realize that some rather important alerts relied on them.

They have been added back with [`e7eaee3`](https://github.com/SteepAtticStairs/AtticRadar/commit/e7eaee358017cf90f3fd3c8d08b2e824734f9525). To access Severe Thunderstorm Watches, you should enable the "Watches" switch, and then disable the "Standard Alerts Only" switch. That last one simply enables / disables alerts that don't have a defined polygon, as explained earlier in this thread. These switches in the settings menu are very likely to change in the future, because the whole system is currently a mess - but I won't push a change to live that disables these new features.

Please let me know if it works now. Thanks!

**Comment by wilburcoding** [comment]
Nice, it's working now! Looks good
![image](https://github.com/SteepAtticStairs/AtticRadar/assets/66228004/a2b9b4a5-2073-4614-8b7a-87461f1c6634)
Texas Storms 👀
